plugins {
    id 'com.android.application'
    id 'com.google.devtools.ksp'
    id 'androidx.room'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'org.jetbrains.kotlin.plugin.serialization'
//    id 'com.google.gms.google-services'
//    id 'com.google.firebase.crashlytics'
}

android {
    namespace 'i.am.shiro.amai'
    compileSdk = 37
    defaultConfig {
        applicationId "i.am.shiro.amai"
        minSdk 30
        targetSdk 36
        versionCode 1
        versionName "1.1"
        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
    buildFeatures {
        // generate BuildConfig class
        buildConfig true
        // enable compose features
        compose true
    }
    room {
        schemaDirectory "$projectDir/schemas"
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation 'androidx.activity:activity-compose:1.13.0'
    implementation 'androidx.navigation3:navigation3-ui:1.1.4'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-navigation3:2.11.0'

    implementation 'androidx.room:room-runtime:2.8.4'
    implementation 'androidx.room:room-paging:2.8.4'
    ksp 'androidx.room:room-compiler:2.8.4'

    implementation 'androidx.paging:paging-runtime:3.5.0'
    implementation 'androidx.paging:paging-common:3.5.0'
    implementation 'androidx.paging:paging-compose:3.5.0'

    // Jetpack Compose
    implementation platform('androidx.compose:compose-bom:2026.06.01')
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material3:material3-adaptive-navigation-suite'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    debugImplementation 'androidx.compose.ui:ui-tooling'

    //    http://square.github.io/retrofit/
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-moshi:3.0.0'

    implementation 'com.squareup.moshi:moshi-kotlin:1.15.2'

    implementation platform('com.squareup.okhttp3:okhttp-bom:5.4.0')
    implementation 'com.squareup.okhttp3:okhttp'
    implementation 'com.squareup.okhttp3:logging-interceptor'

    implementation 'com.google.android.material:material:1.14.0'

    // Firebase
//    implementation platform('com.google.firebase:firebase-bom:26.8.0')
//    implementation 'com.google.firebase:firebase-analytics'
//    implementation 'com.google.firebase:firebase-crashlytics'

    //    https://github.com/JakeWharton/timber
    implementation 'com.jakewharton.timber:timber:5.0.1'

    implementation 'io.coil-kt.coil3:coil:3.5.0'
    implementation 'io.coil-kt.coil3:coil-compose:3.5.0'
    implementation 'io.coil-kt.coil3:coil-network-okhttp:3.5.0'

    implementation 'io.insert-koin:koin-androidx-compose:4.2.2'

    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-core:1.11.0'
}
