import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
    id 'androidx.room'
//    id 'com.google.gms.google-services'
//    id 'com.google.firebase.crashlytics'
}

android {
    namespace 'i.am.shiro.amai'
    compileSdk 35
    defaultConfig {
        applicationId "i.am.shiro.amai"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"
        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
    buildFeatures {
        // generate ViewBinding classes for layouts
        viewBinding true
        // generate BuildConfig class
        buildConfig true
    }
    kotlinOptions {
        freeCompilerArgs += '-Xjspecify-annotations=strict'
        freeCompilerArgs += '-Xcontext-receivers'
    }
    room {
        schemaDirectory "$projectDir/schemas"
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.9.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.fragment:fragment-ktx:1.8.6'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.9.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.0'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-savedstate:2.9.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.room:room-runtime:2.7.1'
    implementation 'androidx.room:room-rxjava3:2.7.1'
    ksp 'androidx.room:room-compiler:2.7.1'

    implementation 'io.reactivex.rxjava3:rxjava:3.1.10'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
    implementation 'io.reactivex.rxjava3:rxkotlin:3.0.1'

    //    http://square.github.io/retrofit/
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-moshi:2.11.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava3:2.11.0'

    implementation 'com.squareup.moshi:moshi-kotlin:1.15.2'

    implementation platform('com.squareup.okhttp3:okhttp-bom:4.10.0')
    implementation 'com.squareup.okhttp3:okhttp'
    implementation 'com.squareup.okhttp3:logging-interceptor'

    implementation 'com.google.android.material:material:1.9.0'

    // Firebase
//    implementation platform('com.google.firebase:firebase-bom:26.8.0')
//    implementation 'com.google.firebase:firebase-analytics'
//    implementation 'com.google.firebase:firebase-crashlytics'

    //    https://github.com/google/flexbox-layout
    implementation 'com.google.android.flexbox:flexbox:3.0.0'

    //    https://github.com/JakeWharton/timber
    implementation 'com.jakewharton.timber:timber:5.0.1'

    implementation 'com.github.lisawray.groupie:groupie:2.10.1'
    implementation 'com.github.lisawray.groupie:groupie-viewbinding:2.10.1'

    implementation 'io.coil-kt:coil:1.4.0'

    implementation 'io.insert-koin:koin-android:3.4.2'
}
